name: notes
description: A Notes App with Firebase and BLoC State Management
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0

  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  shared_preferences: ^2.3.2

  google_fonts: ^6.2.1
  intl: ^0.19.0

  cupertino_icons: ^1.0.8

  image_picker: ^1.1.2
  firebase_messaging: ^15.2.10
  http: ^1.2.0
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^17.2.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/default_avatar.png 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

