// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
final String firebaseProjectId = 'notes-flutter-86dde' ;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQJ67DBDfkBoXpBoFrBrHEV8Ot8rYU_M',
    appId: '1:774560425656:web:19264e329250565bcb764d',
    messagingSenderId: '774560425656',
    projectId: 'notes-flutter-86dde',
    authDomain: 'notes-flutter-86dde.firebaseapp.com',
    storageBucket: 'notes-flutter-86dde.firebasestorage.app',
    measurementId: 'G-4DZX9R3BDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpAqrMsKI9HHKiQP7GqoicOhDZs5gAy5M',
    appId: '1:774560425656:android:a62441bf169e8929cb764d',
    messagingSenderId: '774560425656',
    projectId: 'notes-flutter-86dde',
    storageBucket: 'notes-flutter-86dde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrBGIZYY4azz5tPcbzTLamfo0V1zIoMZs',
    appId: '1:774560425656:ios:91843bed8d3ba199cb764d',
    messagingSenderId: '774560425656',
    projectId: 'notes-flutter-86dde',
    storageBucket: 'notes-flutter-86dde.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrBGIZYY4azz5tPcbzTLamfo0V1zIoMZs',
    appId: '1:774560425656:ios:91843bed8d3ba199cb764d',
    messagingSenderId: '774560425656',
    projectId: 'notes-flutter-86dde',
    storageBucket: 'notes-flutter-86dde.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxQJ67DBDfkBoXpBoFrBrHEV8Ot8rYU_M',
    appId: '1:774560425656:web:a3bdfc666fad973ccb764d',
    messagingSenderId: '774560425656',
    projectId: 'notes-flutter-86dde',
    authDomain: 'notes-flutter-86dde.firebaseapp.com',
    storageBucket: 'notes-flutter-86dde.firebasestorage.app',
    measurementId: 'G-0BGBGELMG4',
  );

}